
services:
  etl:
    image: ${PENTAHO_IMAGE}
    container_name: ${PENTAHO_HOST}
    restart: ${GENERIC_RESTART}
    deploy:
      resources:
        limits:
          cpus: '${PENTAHO_LIMIT_CPU}'
          memory: ${PENTAHO_LIMIT_MEMORY}
    ports:
      - ${PENTAHO_PORT}:8080
    environment:
      CARTE_PASSWORD: ${CARTE_PASSWORD}
      # EMail notification setup
      EMAIL_SMTP_SERVER: ${EMAIL_SMTP_SERVER}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      EMAIL_SENDER_ADDRESS: ${EMAIL_SENDER_ADDRESS}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_SENDER_NAME: ${EMAIL_SENDER_NAME}
      EMAIL_DESTINATION_ADDRESS: ${EMAIL_DESTINATION_ADDRESS}
      # ADempiere Backend connection
      TOKEN: ${PENTAHO_ADEMPIERE_JWT_TOKEN}
      # ADempiere Play Backend
      PLAY_HOST_URL: ${PENTAHO_PLAY_HOST_URL}
      PLAY_OUTPUT_PATH: ${PENTAHO_PLAY_OUTPUT_PATH}
      PLAY_INPUT_PATH: /tmp/play/orders
      # ADempiere Journal Backend
      JOURNAL_SOURCE_DB_HOST: ${PENTAHO_JOURNAL_SOURCE_DB_HOST}
      JOURNAL_SOURCE_DB_PORT: ${PENTAHO_JOURNAL_SOURCE_DB_PORT}
      JOURNAL_SOURCE_DB_NAME: ${PENTAHO_JOURNAL_SOURCE_DB_NAME}
      JOURNAL_SOURCE_DB_USERNAME: ${PENTAHO_JOURNAL_SOURCE_DB_USERNAME}
      JOURNAL_SOURCE_DB_PASSWORD: ${PENTAHO_JOURNAL_SOURCE_DB_PASSWORD}
      JOURNAL_HOST_URL: ${PENTAHO_JOURNAL_HOST_URL}
      JOURNAL_CURRENCY_ISO_CODE: ${PENTAHO_JOURNAL_CURRENCY_ISO_CODE}
      JOURNAL_ORGANIZATION_CODE: ${PENTAHO_JOURNAL_ORGANIZATION_CODE}
    volumes:
      - ${PENTAHO_PLAY_HOST_OUTPUT_PATH}:${PENTAHO_PLAY_OUTPUT_PATH}:rw
      - ${PENTAHO_PLAY_HOST_INPUT_PATH}:${PENTAHO_PLAY_INPUT_PATH}:rw
    networks:
      - shared_network

networks:
  shared_network:
    name: ${ADEMPIERE_NETWORK}
