name: Pentaho PDI Publish

on:
  release:
    types:
      - published

jobs:
  build-pdi-docker-image:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repo
      - name: Checkout Repo
        uses: actions/checkout@v2
      # Get Pentaho PDI Binary
      - name: Get Binary Pentaho PDI
        uses: wei/curl@v1
        with:
          args: -L https://erpya.ams3.digitaloceanspaces.com/public/pdi-ce-9.3.0.0-428-PATCH.zip > pdi-ce-9.3.0.0-428.zip
      # Build Docker Image
      - name: Build Docker Image
        run: docker build -t registry.digitalocean.com/erpya/etl-iancarina:${{ github.event.release.tag_name }} --file docker/Dockerfile .
      # install the doctl on the runner
      - name: Install doctl                 
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      #Push Image to Docker Registry
      - name: push image to digitalocean
        run: |
          doctl registry login
          docker push registry.digitalocean.com/erpya/etl-iancarina:${{ github.event.release.tag_name }}
          docker tag registry.digitalocean.com/erpya/etl-iancarina:${{ github.event.release.tag_name }} registry.digitalocean.com/erpya/etl-iancarina:latest
          docker push registry.digitalocean.com/erpya/etl-iancarina:latest
